#*******************************************************************************
# 
#   check-sentry-action:  github action to check whether a sentry corresponding
#                         to the current commit has been set up in this repo.
#                         The sentry is a build artifact created by the
#                         set-sentry-action and is identified by the commit SHA.
#
#   Outputs: release_not_built which is true if sentry not found, false otherwise
#
# 
#   2022-02-02 Frank Halasz
# 
# 
#   Copyright: 2022 by Interlisp.org 
# 
#
# *****************************************************************************/
name: 'Check build sentry'
description: 'Check for the sentry that indicates that a build with the current commit has already been completed'
inputs:
  tag:
    description: "tag that can distinguish this sentry from other sentries in same workflow"
    required: false
    default: "untagged"
outputs:
  release_not_built:
    description: "Set to 'true' is a release with this commit has not been built"
    value: ${{ steps.sentry.outputs.release_not_built }}
runs:
  using: "composite"
  steps:
    - id: sentry
      run: |
          set +e
          REPO="${{ github.repository }}"
          REPO="${REPO#*/}"
          curl -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository_owner }}/${REPO}/actions/artifacts \
                 2>/dev/null \
              | grep '"name":' | grep -q "sentry-${{ inputs.tag }}-${{ github.sha }}"  
          if [ $? -eq 0 ]; 
           then echo ::set-output name=release_not_built::false;
           else echo ::set-output name=release_not_built::true;
          fi
      shell: bash
